# we want to make sure it is run on trusty where sudo is provided for postgres
dist: xenial
sudo: true
language: python
python:
  - "3.7"
env:
  - DATABASE=postgresql

services:
  - postgresql
  - docker
# make sure we're on the latest version of postgresql
addons:
  postgresql: "10"
before_script:
  - psql -c 'create database guillotina;' -U postgres

install:
  - pip install -r requirements.txt
  - pip install -e .[test]
  - pip install flake8 codecov pytest-cov
script:
  - flake8 guillotina_linkintegrity
  - pytest -s --cov=guillotina_linkintegrity -s --tb=native -v --cov-report term-missing --cov-append ./guillotina_linkintegrity
after_success:
  - codecov

# safelist
branches:
  only:
  - master
