# we want to make sure it is run on trusty where sudo is provided for postgres
language: python
sudo: true
python:
  - "3.6"
sudo: required
env:
  - DATABASE=postgresql
  - DATABASE=cockroachdb

install:
  - pip install -e .[test]
  - pip install flake8 codecov pytest-cov
script:
  - flake8 guillotina_linkintegrity
  - pytest -s --cov=guillotina_linkintegrity -s --tb=native -v --cov-report term-missing --cov-append ./guillotina_linkintegrity
after_success:
  - codecov
